### ISSUE TITLE
Trailing whitespaces on empty lines

### ISSUE THREAD

**Issue by erf** [aude/vis-trailing-whitespace#2]
Hi again,

I tested out the latest version and found an issue.

If you open an empty file and type "i" then "<Enter>" a couple of times and then create some space with "<Space>", you will se the all the empty lines above are highlighted, you should perhaps limit to only whitespace and not newline.

**Comment by aude** [comment]
Hi, thanks! I can reproduce.

Will tweak the pattern to not match empty lines like that.
