### ISSUE TITLE
Highlight style

### ISSUE THREAD

**Issue by erf** [aude/vis-trailing-whitespace#4]
Now the highlight style is the same as the cursor, maybe there is a way to highlight it differently or configure it?

**Comment by aude** [comment]
It looks quite good for me:
![2020-10-30-123838_804x410_scrot](https://user-images.githubusercontent.com/13132188/97700946-ec888880-1aac-11eb-8684-6984d52212bf.png)

I'm using the [solarized](https://github.com/martanne/vis/blob/master/lua/themes/solarized.lua) theme, with a couple of local edits I think.

How does the highlight look at your system?

**Comment by erf** [comment]
It looks pretty good for me too, but it might be fun to style it differently. It seem you can use `style_define` to define new styles. But feel free to close this. Just a suggestion.

**Comment by erf** [comment]
One issue, is if you put your cursor on the highlighted space, you cant see where you are..

**Comment by aude** [comment]
Oh, sorry for not replying sooner to this one. I'll keep it in mind, it could be cool to define our own style instead of copying `STYLE_CURSOR`. Thanks for the idea!

**Comment by erf** [comment]
No worries! I used it on my new plugin [vis-highlight](https://github.com/erf/vis-highlight) where i'm able to highlight arbitrary patterns. I'm wondering if it would be cool to be able to pass a custom style per pattern..
